services:
  ars.command.data_migration:
    public: true
    class: DataMigrationBundle\Command\DataMigrationCommand
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@DataMigrationBundle\Repository\DataMigrationRepository'
      - '@logger'
    tags:
      - console.command
    calls:
      - [ 'setContainer', [ '@service_container' ] ]

  DataMigrationBundle\Repository\DataMigrationRepository:
    public: true
    autowire: true
    tags:
      - doctrine.repository_service
